<!-- app/code/Vendor/Module/view/frontend/web/template/shipping/custom-shipping.html -->
<template>
    <div>
        <input type="checkbox" name="liftgate" data-bind="checked: liftgate" />
        <label for="liftgate">Liftgate</label>
        
        <input type="checkbox" name="delivery_by_mail" data-bind="checked: deliveryByMail" />
        <label for="delivery_by_mail">Delivery by Mail</label>
    </div>
</template>
